### ISSUE TITLE
Unordered list as first level

### ISSUE THREAD

**Issue by nyenye** [andangrd/react-native-markdown-package#15]
How can we show unordered lists as first level (not a sublist). Been trying some things (*, -, +) and none worked out.

**Comment by andangrd** [comment]
HI @nyenye 

I try to use the following code, and it works.

<img width="848" alt="screen shot 2019-02-16 at 11 30 47 pm" src="https://user-images.githubusercontent.com/26213148/52902424-14857900-3243-11e9-8d3f-e6336e58849a.png">

**Comment by nyenye** [comment]
Thanks, templating and vscode was at fault.
