### ISSUE TITLE
strikethrough text is absolutely black

### ISSUE THREAD

**Issue by aviriel** [andangrd/react-native-markdown-package#16]
Is it possible to add support for strike-through text? Now the text is invisible on the black background.

~~Should be like this.~~

**Comment by andangrd** [comment]
@aviriel fix for this will be included in the next release..
sorry for delayed response, :) 

![image](https://user-images.githubusercontent.com/26213148/57759735-c76f5100-7724-11e9-8200-7555adbc6cb8.png)

**Comment by aviriel** [comment]
Thanks a lot!

**Comment by andangrd** [comment]
hi @aviriel ,
fix for this issue is on version 1.4.4
thanks,
