### ISSUE TITLE
markdown parses list

### ISSUE THREAD

**Issue by CSLMeyers** [andangrd/react-native-markdown-package#17]
I have a text like this
 `
- bullet \r- List
1. Numbered\r2. List\r3. List
` ;
after parsed and it shows
• bullet
• List
• Numbered
• List
• List
but I suppose it should be 
• bullet
• List
1. Numbered
2. List
3. List

**Comment by andangrd** [comment]
Hi @CSLMeyers 

Is it something you need? 
![image](https://user-images.githubusercontent.com/26213148/66334715-c81eb300-e963-11e9-9712-087cf00ba950.png)

I have added it to the latest version.
