### ISSUE TITLE
How to use asset images

### ISSUE THREAD

**Issue by winkelsdorf** [andangrd/react-native-markdown-package#19]
Probably I'm missing it, but is there a way to use a callback for using images from the assets? I only stumbled about your `enableLightbox`..

**Comment by andangrd** [comment]
I think we can simply use basic markdown syntax to insert an image.
I have updated the ReadMe, for more detail please check it out..

**Comment by winkelsdorf** [comment]
This question was about _asset_ images, not remote images. I would say that's only possible using a callback to get the asset URL.

_Edit_ (for anybody else searching for a solution): Embedded base64 encoded data images work.

Example:
```markdown
![Plus Sign](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADMAAAAzCAYAAAA6oTAqAAAAEXRFWHRTb2Z0d2FyZQBwbmdjcnVzaEB1SfMAAABQSURBVGje7dSxCQBACARB+2/ab8BEeQNhFi6WSYzYLYudDQYGBgYGBgYGBgYGBgYGBgZmcvDqYGBgmhivGQYGBgYGBgYGBgYGBgYGBgbmQw+P/eMrC5UTVAAAAABJRU5ErkJggg==)
```

Which renders as:
<img width="82" alt="Screen Shot 2019-12-22 at 01 08 19" src="https://user-images.githubusercontent.com/1413291/71315199-90e67b00-2457-11ea-84af-63e1323ee373.png">

But this is more a workaround, as it does not support different resultions (e.g. xxxhdpi, @3) - and you need to embedded them more than once if you have localized markdown files as I do.
