### ISSUE TITLE
componentwillReceiveProps is depreciated

### ISSUE THREAD

**Issue by rogueturnip** [andangrd/react-native-markdown-package#23]
Should look at migrating to getDerivedStateFromProps to support future react native versions.

**Comment by andangrd** [comment]
@rogueturnip can you please inform me where the 'componentwillRecieveProps' is?
I might not remember where it was. I couldn't find it though.

![image](https://user-images.githubusercontent.com/26213148/57761242-53827800-7727-11e9-80e0-f7e31e803c20.png)

thanks
