### ISSUE TITLE
[Question] Custom styling with RN Markdown package

### ISSUE THREAD

**Issue by Minabsapi** [andangrd/react-native-markdown-package#26]
Hello,
I'm currently using this package to parse text with Markdown syntax, however I cannot use custom style (color, font etc.) on `Markdown` elements. 

Is it only me, or this is an unavailable feature ? How could I work around that without dropping this really handy package ?

Thanks in advance for your answer !

**Comment by Minabsapi** [comment]
Noticed you gave the how-to style in the README, how stupid I am :man_facepalming: 
So the color works when wrapping style in `text`, however not the font size property. Is it normal ?

**Comment by Minabsapi** [comment]
`fontSize` property worked finally, however not `textAlign`. Guess it's because the Markdown tag return a `View` rather than `Text`. Any workaround ?

**Comment by KaroUlm** [comment]
Styling like example seems not working in RN 60. I've tried everything, but nothing worked, no color change, no size change. Can anybody help?

**Comment by andangrd** [comment]
Hi @Minabsapi 
sure, you can add style for that view, 
just add something like this in your styles

```
view: {
  alignSelf: 'stretch',
}
```

I have added default styling to be stretched on the latest version.

**Comment by andangrd** [comment]
Hi @KaroUlm ,
Please refer to the latest readme, I have updated it..
I take out the markdown styles, and put it outside the App Styles StyleSheet.create({})
