### ISSUE TITLE
Url not clickable

### ISSUE THREAD

**Issue by hokasan** [andangrd/react-native-markdown-package#3]
Its not possible to click on urls.

react-native: 0.50.4
react-native-markdown-package: 1.0.1

**Comment by hokasan** [comment]
Figured it out, didn't see the onLink props before. Nice! :)

**Comment by andangrd** [comment]
Great..I will close this issue then..

**Comment by andangrd** [comment]
I will update readme soon so that any other people can find all provided props easily.
