### ISSUE TITLE
Remove default use of font Courier

### ISSUE THREAD

**Issue by enguerranws** [andangrd/react-native-markdown-package#30]
Hi,

great work on that package. However, I think something can be improved: this package use Courier as a default font for code / inline code blocks. However, Courier is not available in Android and it throws an error.

I think the styles should check if the platform is iOs before using Courier (or even just simply use `monospace`, not `Courier`);

```
import { Dimensions, StyleSheet, Platform } from 'react-native';
const monospaceFont = Platform.OS === 'ios' ? 'Courier' : 'monospace';
```

**Comment by andangrd** [comment]
@enguerranws Thanks for your feedback.
working on it.
The update will be in the next release.. :)

**Comment by andangrd** [comment]
Hi @enguerranws you can actually pass a custom style to markdown component, though.
However, I have added the default font family 'Monoscape' for android in the latest release, v1.6.0

Thank you for reporting this issue. :)
