### ISSUE TITLE
linkTo not accepting a function

### ISSUE THREAD

**Issue by uxdw** [andangrd/react-native-markdown-package#35]
Readme says 'you could customise the handler for onClick event from the link.'

But cannot find how to do this as only appears to accept the structure:
`onLink={(url) => Linking.openURL(url)}`

Replacing _Linking.openUrl(url)_ with anything else like the below throws an error:
```
onLink={(url) => function () {
    console.log('test');
}}>

onLink={(url) => fn(url)}
```

ERROR:
> TypeError: undefined is not an onbject (evaluating 'opts onLink(target).catch')

The end result ideally would be to utilise a link within the markdown to naviagte to another screen within a ReactNative app.

**Comment by andangrd** [comment]
Hi @uxdw ,

thanks for asking this functionality.

please try again by following this example:

```

const onLinkCallback = (url) => {
  console.log('test test test');

  const isErrorResult = false;

  return new Promise((resolve, reject) => {
    isErrorResult ? reject() : resolve();
  });
};

...

<Markdown
  styles={markdownStyle.collectiveMd}
  onLink={onLinkCallback}>
  {text}
</Markdown>
...


```

`onLinkCallback` should be a function that returns a promise.

thank you
