### ISSUE TITLE
Deprecated View.propTypes

### ISSUE THREAD

**Issue by hokasan** [andangrd/react-native-markdown-package#4]
I think this is deprecated in RN 0.50.4:
view: View.propTypes.style,

It does not give any warnings for me, but on iOS it crashes in release.

**Comment by andangrd** [comment]
@hokasan let me check..

**Comment by andangrd** [comment]
Hi @hokasan ,
kindly check latest version. 1.0.3 and please let me know whether it's still happening on your env or not.
Thanks

**Comment by hokasan** [comment]
It works, thanks!

**Comment by andangrd** [comment]
@hokasan great, I'll close this issue then.
