### ISSUE TITLE
ViewPropTypes no longer supported by react-native-web

### ISSUE THREAD

**Issue by bartvanandel** [andangrd/react-native-markdown-package#40]
This line: https://github.com/andangrd/react-native-markdown-package/blob/812b3a1aba08bf931c647345425992ee15857d09/index.js#L2

causes problems with relatively recent versions of react-native-web. Basically, support for those has been removed in December 2019 (https://github.com/necolas/react-native-web/commit/1ad16930391303da511c98879fa7b2002b28c822).

According to the author, he removed it because react-native will stop supporting it, and he won't put it back (https://github.com/necolas/react-native-web/issues/1543). Not having proptypes isn't really an issue most of the time, so...

Please replace with `PropTypes.shape()`, or remove completely.

**Comment by vanGalilea** [comment]
I'm solving with this [PR](https://github.com/andangrd/react-native-markdown-package/pull/43)

Until then you may use this fork I've created

` "react-native-markdown-package": "https://github.com/vanGalilea/react-native-markdown-package.git",`

**Comment by andangrd** [comment]
PR #43  has been merged and released on the latest version, [v1.8.2](https://github.com/andangrd/react-native-markdown-package/releases/tag/v1.8.2)

Kudos to @vanGalilea ,
