### ISSUE TITLE
ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'

### ISSUE THREAD

**Issue by Andusias** [andangrd/react-native-markdown-package#41]
Hello ! Since the release of React native 0.68 this warning is displayed when I'm opening my app using your package : ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.

Is it possible for you to fix it ? I think you should replace import {ViewPropTypes} from 'react-native' by import {ViewPropTypes} from 'deprecated-react-native-prop-types' in index.js (line 2)

Have a nice day :)

**Comment by andangrd** [comment]
PropTypes has been removed in #43 by @vanGalilea 
please update to the latest version, 

thanks
