### ISSUE TITLE
Crash when using >

### ISSUE THREAD

**Issue by hokasan** [andangrd/react-native-markdown-package#6]
This crashes:
'* Test \n\n>detta är ett test';

This works:
'* Test \n\n >detta är ett test';

For some reason the space before '>' is need or else I get a crash.
Im using 1.0.3.

` 'xxx text: ', '* Test \n\n>detta är ett test'
01-24 16:14:06.769 3747-5461/com.engagingcare E/ReactNativeJS: ReferenceError: Can't find variable: get
 This error is located at: in Markdown (at ArticleBodyText.js:19)`

**Comment by hokasan** [comment]
I see now that blockquotes is work-in-progress, too bad i crashes though....

**Comment by andangrd** [comment]
@hokasan I'm investigating,
